server:
  port: 8082
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 6000
        readTimeout: 6000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000